//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuidMapping.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuidMapping.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 088e3905-0323-4b02-9826-5d99428e115f|Desktop
        ///d3162b92-9365-467a-956b-92703aca08af|Documents
        ///4564b25e-30cd-4787-82ba-39e73a750b14|Recent Items Instance Folder
        ///5b934b42-522b-4c34-bbfe-37a3ef7b9c90|This Device Folder
        ///679f85cb-0220-4080-b29b-5540cc05aab6|Home Folder
        ///85bbd920-42a0-1069-a2e4-08002b30309d|Briefcase
        ///ecdb0924-4208-451e-8ee0-373c0956de16|Work Folders
        ///45c6afa5-2c13-402f-bc5d-45cc8172ef6b|Toshiba Bluetooth Stack
        ///fc9fb64a-1eb2-4ccf-af5e-1a497a9b5c2d|My sharing folders
        ///5fa947b5-650a-4374-8a9a-5e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GuidToName {
            get {
                return ResourceManager.GetString("GuidToName", resourceCulture);
            }
        }
    }
}
